from Assignment1 import *

assert(swap(50,30)==(30,50))
assert(positivenum(1))
assert(divisible(20, 4) == [4, 8, 12, 16, 20])
assert(divide(20,4)==(0,5))
assert(oddnum(5))
assert(seriesofdigits(3)==369)
assert(reversedigit(123)==321)
assert(averagenumber([1,2,3,4,5])==3)
assert(countnumber(1234)==4)
assert(palinum(12321))
assert(replace_value("imAAd is")=="im$$d is")
assert(no_of_vowels("asbiwaveqnfiqeo")==7)
assert(replace_input("Imaad salim shaikh")=="Imaad-salim-shaikh")
assert(occurencenum("imaad","m")==1)

#print(string)
assert(length_string("Hello")==5)
assert(larger_string("Imaad","Imaad Salim")=="Imaad Salim")
print(Count_Upperlower("Imaad Salim"))
assert(counting_digits_chars("ImaadSalim22")==(10,2))
print(tenrandomvalue())
assert(full_pattern("Imaad is from uae","Imaad")==True)
print(randomintegers())
assert(cumulative_sum([1,2,3,4,5])==[1,3,6,10,15])
print(randomvalues())